config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  # Routes to allocation
  get 'allocations/new' => 'allocations#new', :as => 'allocations_new'
  post 'allocations/create' => 'allocations#create', :as => 'allocations_create'
  get 'allocations/devolution/:id' => 'allocations#devolution', :as => 'allocations_devolution'
  
  # Routes to products
  get 'products/index' => 'products#index', :as => 'products_index'
  get 'products/new' => 'products#new', :as => 'products_new'
  post 'products/create' => 'products#create', :as => 'products_create'
  get 'products/edit/:id' => 'products#edit', :as => 'products_edit'
  patch 'products/update/:id' => 'products#update', :as => 'products_update'
  get 'products/destroy/:id' => 'products#destroy', :as => 'products_destroy'

  # Routes to clients
  get 'clients/index' => 'clients#index', :as => 'clients_index'
  get 'clients/new' => 'clients#new', :as => 'clients_new'
  post 'clients/create' => 'clients#create', :as => 'clients_create'
  get 'clients/edit/:id' => 'clients#edit', :as => 'clients_edit'
  patch 'clients/update/:id' => 'clients#update', :as => 'clients_update'
  get 'clients/destroy/:id' => 'clients#destroy', :as => 'clients_destroy'
  get 'clients/show/:id' => 'clients#show', :as => 'clients_show'

  # Routes to user
  get 'users/new' => 'users#new', :as => 'users_new'
  post 'users/create' => 'users#create', :as => 'users_create'
  get 'users/edit' => 'users#edit', :as => 'users_edit'
  patch 'users/update' => 'users#update', :as => 'users_update'
  get 'users/destroy' => 'users#destroy', :as => 'users_destroy'

  # Session routs
  get 'log_out' => 'sessions#destroy', :as => 'log_out'
  get 'log_in' => 'sessions#new', :as => 'log_in'
  post 'init_session' => 'sessions#create', :as => 'sessions_create'
  
  # home page route
  get 'home/index' => 'home#index', :as => 'home'
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :allocation

  validates :name, presence: { message: 'Preencha o seu nome' }
  validates :address, presence: { message: 'Preencha o email' }
  validates :phone, presence: { message: 'Preencha o telefone' }
  validates :phone, phone: { message: 'Telefone inválido' }
  validates :cpf, presence: { message: 'Preencha seu CPF' }
  validates :cpf, uniqueness: { message: 'CPF já cadastrado' }
  validates_cpf_format_of :cpf, :message => 'CPF inválido'

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :autenticated?

  def index
    @clients = Client.all
  end

  def show
    @client = Client.find(params[:id])
  end

  def edit
    @client = Client.find(params[:id])
  end

  def update
    @client = Client.find(params[:id])
    if @client.update(client_params)
      redirect_to home_path, flash: { success: 'Dados atualizados com sucesso' }
    else
      ocurred_errors(@client)
      render :edit
    end
  end

  def destroy
    @client = Client.find(params[:id])
    if @client.destroy
      redirect_to clients_index_path, flash: { success: 'Dados apagados com sucesso' }
    else
      ocurred_errors(current_user)
      render :index
    end
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(client_params)
    if @client.save
      redirect_to clients_index_path, :notice => "Cadastrado com sucesso!"
    else
      ocurred_errors(@client)
      render :new
    end
  end

  private
  
  def client_params
    params[:client].permit(:name, :address, :phone, :cpf)
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/edit.html.erb
<h1>Cadastrar Cliente</h1>

<%= form_for @client, url: clients_update_path do |f| %>
  <%= f.label :name, 'Nome' %><br>
  <%= f.text_field :name %><br>

  <%= f.label :address, 'Endereço' %><br>
  <%= f.text_field :address %><br>

  <%= f.label :phone, 'Telefone' %><br>
  <%= f.text_field :phone %><br>

  <%= f.label :cpf , 'CPF'%><br>
  <%= f.text_field :cpf %><br>
  <%= f.submit 'Alterar'%>

<% end %>

app/views/clients/index.html.erb
<h1>Todos os Clientes</h1>

<%= link_to 'Cadastrar Novo', clients_new_path %>
<table>
  <tr>
    <th>Nome</th>
    <th>Endereço</th>
    <th>Telefone</th>
    <th>CPF</th>
    <th>Ver Locações</th>
    <th>Alterar</th>
    <th>Apagar</th>
  </tr>
  <% @clients.each do |client|%>
    <tr>
    <td><%= client.name %></td>
    <td><%= client.address %></td>
    <td><%= client.phone %></td>
    <td><%= client.cpf %></td>
    <td><%= link_to image_tag('icon_view.png'), clients_show_path(client.id) %></td>
    <td><%= link_to image_tag('icon_edit.png'), clients_edit_path(client.id) %></td>
    <td><%= link_to image_tag('icon_trash.png'), clients_destroy_path(client.id), data: {confirm: "Esta ação não poderá mais ser desfeita. Tem certeza que deseja continuar?"} %></td>
    </tr>
  <% end %>
</table>

app/views/clients/new.html.erb
<h1>Cadastrar Cliente</h1>

<%= form_for @client, url: clients_create_path do |f| %>
  <%= f.label :name, 'Nome' %><br>
  <%= f.text_field :name %><br>

  <%= f.label :address, 'Endereço' %><br>
  <%= f.text_field :address %><br>

  <%= f.label :phone, 'Telefone' %><br>
  <%= f.text_field :phone %><br>

  <%= f.label :cpf , 'CPF'%><br>
  <%= f.text_field :cpf %><br>
  <%= f.submit 'Salvar' %>

<% end %>

app/views/clients/show.html.erb
<h1>Cliente</h1>
<hr>
<table>
  <tr>
    <th>Nome</th>
    <th>Endereço</th>
    <th>Telefone</th>
    <th>CPF</th>
  </tr>
  <tr>
    <td><%= @client.name %></td>
    <td><%= @client.address %></td>
    <td><%= @client.phone %></td>
    <td><%= @client.cpf %></td>
  </tr>
</table>

<h1>Locações Feitas</h1>
<hr>

<table>
  <tr>
    <th>Data do Empréstimo</th>
    <th>Data da devolução</th>
    <th>Produto(quantidade)</th>
  </tr>
  <% @client.allocation.each do |allocation|%>
    <tr>
      <td><%= allocation.allocation_date.to_date %></td>
      <% unless allocation.return_date.nil? %>
        <td><%= allocation.return_date.to_date %></td>
      <% else %>
        <td><%= link_to 'Devolução', allocations_devolution_path(allocation.id) %></td>>
      <% end %>
      <td>
        <% allocation.product_allocation.each do |product_allocation| %>
          <%= product_allocation.product.name %>(<%= product_allocation.amount %>)<br>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>