config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  # Routes to allocation
  get 'allocations/new' => 'allocations#new', :as => 'allocations_new'
  post 'allocations/create' => 'allocations#create', :as => 'allocations_create'
  get 'allocations/devolution/:id' => 'allocations#devolution', :as => 'allocations_devolution'
  
  # Routes to products
  get 'products/index' => 'products#index', :as => 'products_index'
  get 'products/new' => 'products#new', :as => 'products_new'
  post 'products/create' => 'products#create', :as => 'products_create'
  get 'products/edit/:id' => 'products#edit', :as => 'products_edit'
  patch 'products/update/:id' => 'products#update', :as => 'products_update'
  get 'products/destroy/:id' => 'products#destroy', :as => 'products_destroy'

  # Routes to clients
  get 'clients/index' => 'clients#index', :as => 'clients_index'
  get 'clients/new' => 'clients#new', :as => 'clients_new'
  post 'clients/create' => 'clients#create', :as => 'clients_create'
  get 'clients/edit/:id' => 'clients#edit', :as => 'clients_edit'
  patch 'clients/update/:id' => 'clients#update', :as => 'clients_update'
  get 'clients/destroy/:id' => 'clients#destroy', :as => 'clients_destroy'
  get 'clients/show/:id' => 'clients#show', :as => 'clients_show'

  # Routes to user
  get 'users/new' => 'users#new', :as => 'users_new'
  post 'users/create' => 'users#create', :as => 'users_create'
  get 'users/edit' => 'users#edit', :as => 'users_edit'
  patch 'users/update' => 'users#update', :as => 'users_update'
  get 'users/destroy' => 'users#destroy', :as => 'users_destroy'

  # Session routs
  get 'log_out' => 'sessions#destroy', :as => 'log_out'
  get 'log_in' => 'sessions#new', :as => 'log_in'
  post 'init_session' => 'sessions#create', :as => 'sessions_create'
  
  # home page route
  get 'home/index' => 'home#index', :as => 'home'
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :product_allocation
  has_many :allocation, :through => :product_allocation

  validates :name, presence: { message: 'Preencha o nome do Produto' }
  validates :amount, presence: { message: 'Preencha a Quantidade Disponível' }
  validates :amount, numericality: { message: 'Quantidade deve ser numérico' }

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :autenticated?

  def index
    @products = Product.all
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to home_path, flash: { success: 'Dados atualizados com sucesso' }
    else
      ocurred_errors(@product)
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    if @product.destroy
      redirect_to products_index_path, flash: { success: 'Dados apagados com sucesso' }
    else
      ocurred_errors(current_user)
      render :index
    end
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_index_path, :notice => "Cadastrado com sucesso!"
    else
      ocurred_errors(@product)
      render :new
    end
  end

  private
  
  def product_params
    params[:product].permit(:name, :amount)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/edit.html.erb
<h1>Alterar Produto</h1>

<%= form_for @product, url: products_update_path(@product.id) do |f| %>
  <%= f.label :name, 'Nome' %><br>
  <%= f.text_field :name %><br>
  <%= f.label :amount, 'Quantidade'%><br>
  <%= f.text_field :amount %><br>
  <%= f.submit, 'Alterar' %>

<% end %>

app/views/products/index.html.erb
<h1>Todos os produtos</h1>

<%= link_to 'Cadastrar Novo', products_new_path %>
<table>
  <tr>
    <th>Nome</th>
    <th>Quantidade</th>
    <th>Alterar</th>
    <th>Apagar</th>
  </tr>
  <% @products.each do |product|%>
    <tr>
    <td><%= product.name %></td>
    <td><%= product.amount %></td>
    <td><%= link_to image_tag('icon_edit.png'), products_edit_path(product.id) %></td>
    <td><%= link_to image_tag('icon_trash.png'), products_destroy_path(product.id), data: {confirm: "Esta ação não poderá mais ser desfeita. Tem certeza que deseja continuar?"} %></td>
    </tr>
  <% end %>
</table>

app/views/products/new.html.erb
<h1>Cadastrar Produto</h1>

<%= form_for @product, url: products_create_path do |f| %>
  <%= f.label :name, 'Nome' %><br>
  <%= f.text_field :name %><br>
  <%= f.label :amount , 'Quantidade'%><br>
  <%= f.text_field :amount %><br>
  <%= f.submit 'Salvar%>

<% end %>